/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monedas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author TOSHIBA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    double total;
    
    double[][] dispensador = null;
    double[][] resultado = null;
    int[][] arrayLimpio = null;
    
    
    public Main() {
        initComponents();
        SNumeros(jtxCambio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbejemplo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSolucion = new javax.swing.JTextArea();
        jtxCambio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Máquina expendedora");

        jLabel2.setText("Cantidad a devolver");

        jLabel3.setText("Disposición del cajero");

        jcbejemplo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ejemplo 1", "ejemplo 2" }));

        jLabel4.setText("SOLUCIÓN");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtaSolucion.setColumns(20);
        jtaSolucion.setRows(5);
        jScrollPane1.setViewportView(jtaSolucion);

        jtxCambio.setText("0");
        jtxCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxCambioKeyTyped(evt);
            }
        });

        jLabel5.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jcbejemplo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SNumeros (final JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped (KeyEvent e) {
                char c = e.getKeyChar();
                int k = (int) e.getKeyChar();
                if((!Character.isDigit(c))&& (k!=46)){
                    getToolkit().beep();
                    e.consume();
                } else {
                    if(k==46) { //es el codigo ASCII del punto para usar DOUBLE
                        String dato = a.getText();
                        int tama = dato.length();
                        for (int i = 0; i <= tama; i++) {
                            if(dato.contains(".")){
                                getToolkit().beep();
                                e.consume();
                            }
                        }
                    }                        
                }                    
            }
        });        
    }
    
    
    public int[][] leerFichero (File archivo){ 
        
        try{            
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            dispensador = new double[2][15];
            int contadorPos2 = 0;
            boolean primera =true;
            while ((linea=br.readLine())!=null) {                                    
                //System.out.println(linea);
                if(linea.charAt(0)!='/'){
                     if (primera){
                         dispensador[0][contadorPos2]=Double.parseDouble(linea);
                         primera = false;
                     } else{
                         dispensador[1][contadorPos2]=Double.parseDouble(linea);
                         contadorPos2++;
                         primera=true;
                     }
                } 
            }
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        int j = 0;
        for (int i = 0; i < dispensador[0].length; i++) {
            if (dispensador[1][i]!= 0.0){                
                j++;
            }
            
        }
        
        arrayLimpio = new int [2][j];
        j = 0;
        for (int i = 0; i < dispensador[0].length; i++) {
            if (dispensador[1][i]!= 0.0){
                arrayLimpio[0][j] = (int) (dispensador[0][i]*100);
                arrayLimpio[1][j] = (int) (dispensador[1][i]);
                j++;
            }
            
        }
        
        return arrayLimpio;
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:      
        
        
        total = Double.parseDouble(jtxCambio.getText());
        int devuelto = 0;
        
        int totalModificado = (int) (total*100);
        
        switch(jcbejemplo.getSelectedItem().toString()){
            case "ejemplo 1": {
                    File fis = new File("C:/Users/TOSHIBA/Documents/NetBeansProjects/Monedas/ej1");
                    leerFichero(fis);                   
                    //vo.escribir(leerFichero(fis));
                    Voraz vo = new Voraz();
                    if (vo.devolverCambio(totalModificado, arrayLimpio, arrayLimpio[0].length)){
                        resultado = vo.getResultado();
                        //INTENTAR CORTAR EL ARRAY
                        jtaSolucion.append("Si es posible por Voraz\n");
                        int i =0;
                        jtaSolucion.append(Arrays.toString(resultado[i]));
                        jtaSolucion.append("\n");
                        i = 1;
                        jtaSolucion.append(Arrays.toString(resultado[i])); 
                        jtaSolucion.append("\n");
                        
                    } else {
                        jtaSolucion.append("No es posible resolver con VORAZ \n");
                    }
                    
                    DyV dv = new DyV();
                    //File fis = new File("C:/Users/TOSHIBA/Documents/NetBeansProjects/Monedas/ej1");
                    leerFichero(fis);
                    if (dv.devolverCambio(totalModificado, arrayLimpio, devuelto, arrayLimpio[0].length, arrayLimpio, arrayLimpio[0].length)){
                        //System.out.println("D y V correcto");
                        resultado = vo.getResultado();
                        //INTENTAR CORTAR EL ARRAY
                        jtaSolucion.append("Si es posible con D y V\n");
                        int i =0;
                        jtaSolucion.append(Arrays.toString(resultado[i]));
                        jtaSolucion.append("\n");
                        i = 1;
                        jtaSolucion.append(Arrays.toString(resultado[i])); 
                        jtaSolucion.append("\n");
                        
                    } else {
                        jtaSolucion.append("No es posible resolver con DYV \n");
                    }
                    
                    }
                    break;
                        
            case "ejemplo 2": {
                    File fis = new File("C:/Users/TOSHIBA/Documents/NetBeansProjects/Monedas/ej2");
                    leerFichero(fis);
                    Voraz vo = new Voraz();
                    if (vo.devolverCambio(totalModificado, arrayLimpio, arrayLimpio[0].length)){
                        resultado = vo.getResultado();
                        //INTENTAR CORTAR EL ARRAY
                        jtaSolucion.append("Si voraz\n");
                        int i =0;
                        jtaSolucion.append(Arrays.toString(resultado[i]));
                        jtaSolucion.append("\n");
                        i = 1;
                        jtaSolucion.append(Arrays.toString(resultado[i])); 
                        jtaSolucion.append("\n");
                        
                    } else {
                        jtaSolucion.append("No es posible resolver con VORAZ\n");
                    }
                    
                    DyV dv = new DyV();
                    //File fis = new File("C:/Users/TOSHIBA/Documents/NetBeansProjects/Monedas/ej1");
                    leerFichero(fis);
                    if (dv.devolverCambio(totalModificado, arrayLimpio, devuelto, arrayLimpio[0].length, arrayLimpio, arrayLimpio[0].length)){
                        //System.out.println("D y V correcto");
                        resultado = vo.getResultado();
                        //INTENTAR CORTAR EL ARRAY
                        jtaSolucion.append("Si es posible con D y V\n");
                        int i =0;
                        jtaSolucion.append(Arrays.toString(resultado[i]));
                        jtaSolucion.append("\n");
                        i = 1;
                        jtaSolucion.append(Arrays.toString(resultado[i])); 
                        jtaSolucion.append("\n");
                        
                    } else {
                        jtaSolucion.append("No es posible resolver con DYV \n");
                    }
                    
                    }
                    break;
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxCambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCambioKeyTyped
      
    }//GEN-LAST:event_jtxCambioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbejemplo;
    private javax.swing.JTextArea jtaSolucion;
    private javax.swing.JTextField jtxCambio;
    // End of variables declaration//GEN-END:variables
}
